version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: telegram_file_manager_bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      - ./downloads:/app/downloads
      - ./extracted:/app/extracted
      - ./temp:/app/temp
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge